### PR TITLE
Update Dataset link, Acknowledgement and Disclosure of funding section

### PR DESCRIPTION
**Pull request by egrace479**
Adjusts dataset download link to point to the dataset on Hugging Face.

Adds full information for Imageomics and ICICLE to Acknowledgement and Disclosure of funding section along with link to Mpala.

### CODE REVIEW

**Comment by egrace479** [comment]
@dirtmaxim please review and update

**Comment by dirtmaxim** [comment]
@egrace479 Can you please change the links: Download KABR from Google Drive and Download KABD from Hugging Face?

**Comment by egrace479** [comment]
@dirtmaxim why do you still want to have the Google Drive download when we have HF set up?

**Comment by dirtmaxim** [comment]
@egrace479 Just as an alternative.

**Comment by dirtmaxim** [comment]
@egrace479 I will update it myself.

**Pull request merged**
